img_size: [120,160]
top_cutoff: 40

detector: 
  - line_detector.LineDetectorHLS
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [60,150]
      hough_threshold: 20
      hough_min_line_length: 3
      hough_max_line_gap:    1

      hls_white1:  [0,180,0]
      hls_white2:  [100,255,255]
      hls_yellow1: [10,100,150]
      hls_yellow2: [40,180,255]
      hls_red1:    [165,100,100]
      hls_red2:    [180,255,255]