img_size: [120,160]
top_cutoff: 40

detector: 
  - line_detector.LineDetectorHLS
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [80,200]
      hough_threshold: 2
      hough_min_line_length: 3
      hough_max_line_gap:    1

      hls_white1:  [0,175,0]
      hls_white2:  [100,255,255]
      hls_yellow1: [25,100,200]
      hls_yellow2: [35,190,255]
      hls_red1:    [165,100,100]
      hls_red2:    [180,255,255]
